name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: Run yarn commitlint --from=head_commit.message
        run: echo "${{ github.event.head_commit.message }}" | yarn commitlint
      - run: yarn prettier --check .
      - run: yarn cspell --no-must-find-files '**'
      - run: yarn build
